port: COM3 #COM1 /dev/....
baudrate: 9600
databits: 8
parity: none # none even mark odd space
stopbits: 1 #0 1 1.5 2
homeassistant_auto_discovery_prefix: "homeassistant" #default: homeassistant
slave:
  - name: Eastron Test
    type: EastronSDM120 #Based on filename in the DeviceTemplates folder, filename without .yml
    slave_id: 1 #Slave ID for this device
    polling_interval: 10000 #in milliseconds - how fast should the device be queried
    priority: 1 #highest will always be executed first when the bus is becoming saturated
    include: "" #Only include these measuremeants (see device template). Seperate by ;
    exclude: "voltage" #exclude these measuremeants (see device template). Seperate by ;
mqtt:
  server: 192.168.2.35 #Mqtt host
  port: 1883 #Mqtt port
  username: "" #Mqtt username
  password: "" #Mqtt password
  tls: false #Use TLS certificate
  client_id: "development" #Mqtt client id  - needs to be unique!
  main_topic: "modbus2mqtt-dev" #post values to main_topic/#
