port: COM5 #COM1 /dev/....
baudrate: 9600
databits: 8
parity: none # none even mark odd space
stopbits: 1 #0 1 1.5 2
slave:
  - name: eastron_test
    type: EastronSDM120
    slave_id: 1
    polling_interval: 10000 #ms
    priority: 1 #highest will always be executed first
    include: ""
    exclude: "voltage"
mqtt:
  server: 192.168.2.35
  port: 1883
  username: "" 
  password: ""
  tls: false
  client_id: "development"
  main_topic: "modbus2mqtt-dev"